# Generated by Django 3.2.4 on 2021-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppinglist_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
