# Generated by Django 3.2.4 on 2021-06-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shoppinglist_app", "0003_shoppinglist_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppinglist",
            name="name",
        ),
    ]
