# Generated by Django 3.2.4 on 2021-07-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoppinglist_app", "0004_remove_shoppinglist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglist",
            name="check",
            field=models.BooleanField(default=False),
        ),
    ]
